### ISSUE TITLE
nn.SpatialSoftMax breaking

### ISSUE THREAD

**Issue by shubhamjain0594** [torch/cunn#292]
```
require 'nn'
require 'cunn'

softOutCalc = nn.Sequential():add(nn.SpatialSoftMax())
softOutCalc = softOutCalc:cuda()
ips = torch.rand(8,2,80,80)
ips = ips:cuda()
softOutCalc:forward(ips)
```

This code gives the error 

> THCudaCheck FAIL file=/tmp/user/1012/luarocks_cutorch-scm-1-199/cutorch/lib/THC/generic/THCTensorCopy.c line=81 error=77 : an illegal memory access was encountered
/home/users/shubhamj/torch/install/bin/luajit: cuda runtime error (77) : an illegal memory access was encountered at /tmp/user/1012/luarocks_cutorch-scm-1-199/cutorch/lib/THC/generic/THCStorage.c:158

It used to work fine on earlier installations.

**Comment by fmassa** [comment]
I just tried the snippet using most recent installations of `cutorch` and `cunn` and it works fine for me.

**Comment by shubhamjain0594** [comment]
I have updated to the latest version. Still getting same errors. Any help is appreciated. 
I am working with cuda7.5 and latest installs of torch, cutorch, nn, cunn and cudnn.

**Comment by soumith** [comment]
Shubham, is this still a blocker? if so i can have a look.

Give me info on your GPU model (of all GPUs on system) and NVIDIA driver.

**Comment by shubhamjain0594** [comment]
Its working fine. Thanks

**Comment by chsasank** [comment]
I have the exact same issue. So, reopening the issue.

**Comment by chsasank** [comment]
Let me give more cases with cudnn:

```
require 'nn'
require 'cunn'
require 'cudnn'

softOutCalc = nn.Sequential():add(nn.SpatialSoftMax())
softOutCalc = softOutCalc:cuda()
softOutCalc = cudnn.convert(softOutCalc, cudnn)  
ips = torch.rand(8,2,80,80)
ips = ips:cuda()
softOutCalc:forward(ips)
```
Gives
```
THCudaCheck FAIL file=/home/users/sasank/torch/extra/cutorch/lib/THC/generic/THCStorage.c line=147 error=77 : an illegal memory access was encountered
```

While, 
```
require 'nn'
require 'cunn'
require 'cudnn'

softOutCalc = nn.Sequential():add(cudnn.SpatialSoftMax())
softOutCalc = softOutCalc:cuda()
ips = torch.rand(8,2,80,80)
ips = ips:cuda()
softOutCalc:forward(ips)
```
Works

**Comment by soumith** [comment]
oh cool. so cudnn.convert is screwing something up. that's very helpful to figure out a fix. thanks.

**Comment by soumith** [comment]
ok nevermind, it's not even cudnn.convert. the code has a bug.

**Comment by soumith** [comment]
pushed a fix. reinstalling cunn fixes it.
