### ISSUE TITLE
SpatialMaxsampling: too many resources requested for launch

### ISSUE THREAD

**Issue by Atcold** [torch/cunn#32]
I'm running a very tiny network (3-layer ConvNet with few tens of fiters) on a Nvidia Jetson TK1 with Ubuntu 14.04, Cuda 6.0 and the latest drivers (`R19.3.0_armhf`).
If I use the CPU, everything works fine and the feedforward step is completed in 10s of ms.
If I try to use the GPU (using `nn.SpatialConvolutionMM` and `nn.SpatialMaxPooling`), I get the following error message I do not understand:

``` lua
error in SpatialMaxsampling.updateOutput: too many resources requested for launch
/usr/local/bin/luajit: /usr/local/share/lua/5.1/nn/SpatialMaxPooling.lua:18: aborting   
stack traceback:                                                                        
        [C]: in function 'SpatialMaxPooling_updateOutput'                               
        /usr/local/share/lua/5.1/nn/SpatialMaxPooling.lua:18: in function 'updateOutput'
        /usr/local/share/lua/5.1/nn/Sequential.lua:37: in function 'forward'            
        ./src/profileNet.lua:32: in function 'time'                                     
        general-profiler.lua:33: in main chunk                                          
        [C]: in function 'dofile'                                                       
        /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:129: in main chunk             
        [C]: at 0x0000cf89                                                              
```

Running the same code on a Intel machine with Ubuntu 14.04 and a GeForce GTX 780 this doesn't happen. A similar error, though, happened on another Intel machine with Ubuntu 14.04 and a Tesla K40c while trying to run OverFeat.

Moreover, this error does not happen if I load the model and process the `SpatialMaxPooling` layer only. Instead, if I run all the previous layers, one by one, then it fails at the `SpatialMaxPooling` one with the "too many resources requested for launch" Cuda error message.

I believe it has to do something with the registers available per block. Perhaps the TK1 has more limited resources and the `SpatialMaxsampling` is trying to allocate too many registers.

**Comment by N1col4s** [comment]
I got the same issue.
Any idea?

**Comment by soumith** [comment]
on the Tegra, this likely is a block limitation. CuDNN is much more well-written for this.

**Comment by Atcold** [comment]
In fact, we are using *CUDNN*. Although now, we have to "convert" networks that we care to run on the Tegra TK1 platform.
It would be very nice being able to simply run the same net on all our platforms...

**Comment by N1col4s** [comment]
I installed CUDNN on TK1.
When i run this simple code : 

require("cudnn")

local net = nn.Sequential()
net:add(cudnn.SpatialConvolution(3, 48, 5, 5, 1, 1, 0, 0))
net:add(cudnn.ReLU())
net:add(cudnn.SpatialMaxPooling(2, 2, 2, 2))
net = net:cuda()

local input = torch.Tensor(128, 3, 231, 231):cuda()
net:forward(input)

i got "Killed" as a result :(

**Comment by Atcold** [comment]
@culurciello, see, others have issues with this platform.

**Comment by culurciello** [comment]
SpatialMaxPooling calls too many resources, and Tegra K1 cannot provide them.
The code needs to be modified and check for platform resource constrains.
In the meantime, we got it to work using CUDNN

**Comment by Atcold** [comment]
@culurciello, he used `cudnn` (see his snippet above).

**Comment by N1col4s** [comment]
After checking ram during process, indeed i got a lack of ram to execute completly the program.

**Comment by el-oso** [comment]
Hi guys, perhaps this issue is cold now. I ran into the same error message while running the CuDNN tests and I wonder if there is a follow up on this?

**Comment by ChrisYang** [comment]
Same issue here. Any update? 
Also it seems current torch7 requires cuDNN 4 (CUDA7.0 ) but TK1 only supports CUDA 6.5 and cuDNN 6.5.

**Comment by Atcold** [comment]
@chrisyang, `cunn` does not require *cuDNN* libraries; `cudnn` does. Anyhow, we've moved to the TX1 now.

**Comment by verdimrc** [comment]
In case it's still relevant, identify the kernel that fails to launch, then modify the kernel to include `__launch_bounds__` directive.

What I found after hunting down this kind of errors is that even if the error message mentions `SpatialMaxsampling.updateOutput`, the error is actually caused by failure to launch a kernel by the preceding layer.

Therefore, it could be worthwhile to look the preceding layer of `SpatialMaxsampling` and figure out what kernels it launches.

Another helpful way is to compare the execution profile (collected using `nvprof --print-gpu-trace`), then compared it to the profile of a successful execution (i.e., using `cunn` build with `-maxrregcount <n>`).
